# Generated by Django 5.1.6 on 2025-04-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("laboratory", "Laboratory"),
                            ("consumables", "Consumables"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
