# Generated by Django 5.1.6 on 2025-03-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("full_name", models.CharField(max_length=255)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("age", models.IntegerField()),
                ("date_of_birth", models.DateField()),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "patient",
            },
        ),
    ]
