# Generated by Django 5.1.6 on 2025-03-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={},
        ),
        migrations.AlterModelManagers(
            name="doctor",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
