# Generated by Django 5.1.6 on 2025-03-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_system", "0002_alter_doctor_options_alter_doctor_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
