# Generated by Django 5.1.6 on 2025-03-24 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_system", "0003_alter_doctor_username"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="doctor",
            table="doctors",
        ),
    ]
