# Generated by Django 5.1.6 on 2025-04-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_system", "0004_alter_doctor_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("security_question", models.CharField(max_length=255)),
                ("security_answer", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[("doctor", "Doctor"), ("nurse", "Nurse")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
    ]
